FROM ghcr.io/abdeladim88/sd-auto-webui:master

# تثبيت إضافات ControlNet و IP-Adapter
RUN git clone https://github.com/Mikubill/sd-webui-controlnet.git /stable-diffusion-webui/extensions/sd-webui-controlnet && \
    git clone https://github.com/ExponentialML/IPAdapter-webui.git /stable-diffusion-webui/extensions/IPAdapter-webui

# إعداد الـ API ليعمل على RunPod Serverless
ENV CLI_ARGS="--port 3000 --api --xformers --enable-insecure-extension-access --skip-torch-cuda-test"

EXPOSE 3000

CMD ["python3", "launch.py", "--listen"]
