FROM runpod/stable-diffusion:web-ui-10.2.1

USER root

# تثبيت git عشان نقدر نعمل clone من GitHub
RUN apt update && apt install -y git

# ControlNet
RUN rm -rf /stable-diffusion-webui/extensions/sd-webui-controlnet && \
    git clone https://github.com/Mikubill/sd-webui-controlnet.git /stable-diffusion-webui/extensions/sd-webui-controlnet

# IP-Adapter
RUN rm -rf /stable-diffusion-webui/extensions/IPAdapter-webui && \
    git clone https://github.com/ExponentialML/IPAdapter-webui.git /stable-diffusion-webui/extensions/IPAdapter-webui

# مجلدات النماذج
RUN mkdir -p /stable-diffusion-webui/extensions/sd-webui-controlnet/models && \
    mkdir -p /stable-diffusion-webui/models/IP-Adapter

# تهيئة التشغيل API فقط
ENV CLI_ARGS="--port 3000 --api --xformers --enable-insecure-extension-access --skip-torch-cuda-test"
EXPOSE 3000

CMD ["python3", "launch.py", "--listen"]
